# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_SUNXI_CEDRUS) += sunxi-cedrus.o

sunxi-cedrus-y = cedrus.o \
		 cedrus_context.o \
		 cedrus_dec.o \
		 cedrus_dec_h264.o \
		 cedrus_dec_h265.o \
		 cedrus_dec_mpeg2.o \
		 cedrus_dec_vp8.o \
		 cedrus_enc.o \
		 cedrus_engine.o \
		 cedrus_proc.o
